#!/bin/bash

# this script is for the LESSOPEN env var, and is an "input pipe". it allows
# less to read archives, pdfs (with pdftotext), and will use lynx -dump for html
# to use it, set LESSOPEN='|lessopen %s'
exec 2>/dev/null

shopt -s nocasematch

if [[ $1 = *.tar* ]]; then
  if [[ $1 = *z ]]; then
    tar tz "$1"
  else
    tar t "$1"
  fi

  return
fi

case "$1" in
  *.gz) zcat "$1";;
  *.xz) xzcat "$1";;
  *.zip) unzip -p "$1";;
  *.pdf) pdftotext -layout -nopgbrk "$1" -;;
  *.html) lynx -dump "$1";;
  *) cat "$1";;
esac



# Copyright Daniel Mills <dm@e36freak.com>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
