#!/bin/bash

shopt -s nullglob extglob

noclobber() {
  local out=$1 i=0
  
  if [[ $out = *+([^/]).*([^/]) ]]; then
    local base=${1%.*} ext=${1##*.}

    while [[ -e $out ]]; do
      out=$base.$((++i)).$ext
    done
  else
    while [[ -e $out ]]; do
      out=$1.$((++i))
    done
  fi

  printf '%s\n' "$new"
}

files=("${@:1:$#-1}")
target="${!#}"

if [[ -d $target ]]; then
  for f in "${files[@]}"; do
    [[ -e $f ]] || {
      echo "$f does not exist, skipping" >&2
      continue
    }

    cp "$f" "$(noclobber "$target/$f")" || {
      echo "error copying $f to $target/$f, skipping" >&2
      continue
    }
  done
else
  for f in "${files[@]}"; do
    [[ -e $f ]] || {
      echo "$f does not exist, skipping" >&2
      continue
    }

    cp "$f" "$(noclobber "$target")" || {
      echo "error copying $f to $target/$f, skipping" >&2
      continue
    }
  done
fi



# Copyright Daniel Mills <dm@e36freak.com>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
